### ISSUE TITLE
Sorting arrows don't toggle

### ISSUE THREAD

**Issue by sergeychernyshev** [siakaramalegos/shopify-themes-performance#1]
Sorting arrows in the table header don't toggle ASC/DESC sorting when pressed repeatedly, so table can only be ordered in one direction at the moment.
<img width="1348" alt="2024-09-18_10-26-19" src="https://github.com/user-attachments/assets/32c9d6a1-56d9-4b62-a279-286ba5f2d128">

**Comment by siakaramalegos** [comment]
Yeah, those buttons were misleading. The intention was to only be able to sort in a positive direction to keep the vibes more positive. :) I changed the UI to make this more obvious and also to enable it on mobile.
